project:
  type: website
  output-dir: docs
resources:
  - CNAME
website:
  title: "Stefan Eng"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/stefaneng
      - icon: linkedin
        href: https://www.linkedin.com/in/stefaneng13/
format:
  html:
    theme: lux
    css: styles.css
execute:
  freeze: auto
editor: source

